<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../BuildingBlocks/SmartCity.BuildingBlocks/SmartCity.BuildingBlocks.csproj" />
    <ProjectReference Include="../../../SmartCity.Contracts.Grpc/SmartCity.Contracts.Grpc.csproj" />
  </ItemGroup>
</Project>
